source: source
destination: public
markdown: rdiscount
pygments: false
permalink: pretty

url: http://alvinlai.com
title: Alvin Lai
author: Alvin Lai
email: al@alvinlai.com #Add your email (optional) for the atom feed
simple_search: http://google.com/search

recent_posts: 5

twitter_user: alvinlai
tweet_count: 5
show_replies: false

delicious_user:
delicious_count: 

pinboard_user: 
pinboard_count: 

disqus_short_name: 

google_analytics_tracking_id: UA-22731879-4

